<script setup lang="ts">
import {computed,ref} from 'vue'
import {configurationChanges,display} from '@/utils/configurationText'
export interface AuditEntry {id:number;time:number;actor:string;action:string;target:string;detail:Record<string,unknown>}
const props=defineProps<{logs:AuditEntry[]}>()
const query=ref('')
const actions:Record<string,string>={enroll:'设备接入',configure:'修改设备配置',reload:'远程刷新',rollback:'回退配置','batch-config':'批量配置',template:'新建旧配置模板','template-edit':'修改旧配置模板','catalog-create':'新建模板草稿','catalog-edit':'编辑模板草稿','catalog-publish':'发布模板版本','catalog-archive':'归档模板','hardware-test':'登记硬件实测','asset-upload':'上传背景图片',deploy:'更新设备配置',deployment:'部署软硬件模板','configuration-adopt':'转换历史配置','policy-apply':'应用房间规则','room-policy':'修改房间核验或规则',role:'调整账号权限',login:'登录',logout:'退出登录'}
const rows=computed(()=>props.logs.filter(r=>`${r.detail.actor_name||r.actor} ${actions[r.action]||r.action} ${r.detail.target_name||r.target} ${r.detail.room_name||''} ${r.detail.device_code||''}`.toLowerCase().includes(query.value.toLowerCase())))
function changes(row:AuditEntry){return configurationChanges((row.detail.before||{}) as Record<string,unknown>,(row.detail.after||{}) as Record<string,unknown>)}
</script>
<template><section class="v6-card"><div class="v6-toolbar"><input v-model="query" aria-label="搜索操作记录" placeholder="按姓名、设备、会议室或操作搜索" /><span class="v6-muted">最近 {{logs.length}} 条操作</span></div><div class="v6-table-wrap"><table><thead><tr><th>时间</th><th>操作人</th><th>操作内容</th><th>对象与变更</th></tr></thead><tbody><tr v-for="log in rows" :key="log.id"><td>{{new Date(log.time*1000).toLocaleString()}}</td><td>{{log.detail.actor_name||({control:'主控管理员',system:'系统任务',migration:'配置迁移'}[log.actor]||'历史身份')}}</td><td>{{actions[log.action]||'历史操作'}}<small v-if="log.detail.state">{{display(log.detail.state)}}</small></td><td><strong>{{log.detail.target_name||log.detail.room_name||'历史对象'}}</strong><small v-if="log.detail.room_name">{{log.detail.room_name}} · {{log.detail.location}}</small><small v-if="log.detail.hardware_name">硬件：{{log.detail.hardware_name}} v{{log.detail.hardware_version}}</small><small v-if="log.detail.software_name">软件：{{log.detail.software_name}} v{{log.detail.software_version}}</small><small v-if="log.detail.error">{{log.detail.error}}</small><details><summary>变更明细</summary><p v-for="change in changes(log)" :key="change">{{change}}</p><p v-if="!changes(log).length">{{log.detail.notes||'此记录没有保存字段变更明细。'}}</p><small>排查编号：{{log.id}} · {{log.action}} · {{log.target}} · {{log.actor}}</small></details></td></tr></tbody></table></div></section></template>
