export interface Rules {owner:'official'|'v5';mode:'off'|'observe'|'auto';early_minutes:number;grace_minutes:number;release_delay_seconds:number}
export interface HardwareSpec {manufacturer:string;model:string;firmware:string;device_profile:string;portrait:boolean;width:number;height:number;room_light:boolean;pins:{red:number;green:number;blue:number};active_level:number;notes:string}
export interface SoftwareSpec {layout:'standard'|'compact';orientation:'any'|'landscape'|'portrait';min_width:number;min_height:number;theme_mode:'auto'|'light'|'dark';language:'zh-CN'|'en';background_day:string;background_night:string;background_fit:'cover'|'contain';rules:Rules}
export interface TemplateVersion {template_id:string;version:number;name:string;spec:HardwareSpec|SoftwareSpec;actor:string;created_at:number}
export interface CatalogTemplate {id:string;kind:'hardware'|'software';name:string;spec:HardwareSpec|SoftwareSpec;revision:number;published_version:number;archived:number;source:string;versions:TemplateVersion[];tests:{id:string;version:number;actor:string;created_at:number;value:{device_code:string;result:string;notes:string}}[];devices:{id:string;code:string;room_id:string;version:number}[];rooms:{room_id:string;room_name:string;location:string;version:number}[]}
export interface RoomConfiguration {room_id:string;software_id:string;software_version:number;revision:number;controller_id:string;rules:Rules;policy_state:string;error:string;room_name:string;location:string}
export interface Installation {device_id:string;hardware_id:string;hardware_version:number;deployment_id:string}
export interface Deployment {id:string;device_id:string;room_id:string;hardware_id:string;hardware_version:number;software_id:string;software_version:number;device_revision:number;reported_revision:number;state:string;online:boolean;policy_state:string;error:string;created_at:number;value:{device_code:string;room_name:string;location:string;hardware_name:string;software_name:string;before:Record<string,unknown>;after:Record<string,unknown>}}
export interface Configuration {rooms:Record<string,RoomConfiguration>;devices:Record<string,Installation>;deployments:Deployment[]}
export const emptyConfiguration=():Configuration=>({rooms:{},devices:{},deployments:[]})
export const hardwareDefaults=():HardwareSpec=>({manufacturer:'',model:'',firmware:'',device_profile:'generic',portrait:false,width:0,height:0,room_light:false,pins:{red:148,green:154,blue:147},active_level:0,notes:''})
export const softwareDefaults=():SoftwareSpec=>({layout:'standard',orientation:'any',min_width:0,min_height:0,theme_mode:'auto',language:'zh-CN',background_day:'',background_night:'',background_fit:'cover',rules:{owner:'official',mode:'off',early_minutes:5,grace_minutes:10,release_delay_seconds:60}})
export const stateLabel=(state:string)=>({inactive:'设备已停用',waiting:'等待设备应用',partial:'部分生效',failed:'应用失败',applied:'全部生效',blocked:'待完成房间核验',pending:'等待规则应用',superseded:'已被后续部署替代',drifted:'配置已在其他入口改变'}[state]||state)
export function templateName(catalog:CatalogTemplate[],id?:string,version?:number){const t=catalog.find(t=>t.id===id);return t ? `${t.versions.find(v=>v.version===version)?.name||t.name} · v${version}` : '尚未关联模板'}
