import {test,expect} from '@playwright/test'
import {fixture,selectDeployment} from './configuration.fixture'
test('地区后只出现下级位置，任意深度筛选不会重复祖先',async({page})=>{
 await fixture(page);await page.goto('/control');await page.getByLabel('地区',{exact:true}).selectOption('bj');await expect(page.locator('tbody tr')).toHaveCount(2)
 await expect(page.getByLabel('园区 / 楼栋')).not.toContainText('公司');await expect(page.getByLabel('园区 / 楼栋')).not.toContainText('北京')
 await page.getByLabel('园区 / 楼栋').selectOption('bja');await page.getByLabel('楼层',{exact:true}).selectOption('bja2');await page.getByLabel('下级位置 3').selectOption('bja2e');await expect(page.locator('tbody tr')).toHaveCount(1)
 const panel=await selectDeployment(page);await panel.getByLabel('园区 / 楼栋').selectOption('bjb');await expect(panel.getByLabel('下级位置 3')).toHaveCount(0);await expect(panel.getByLabel('分配会议室')).toHaveValue('');await panel.getByLabel('地区',{exact:true}).selectOption('sh');await panel.getByLabel('分配会议室').selectOption('omm_shanghai');await panel.getByLabel('会议室关键词').fill('不存在');await expect(panel.getByLabel('分配会议室')).toHaveValue('')
})
test('软件模板保存草稿、发布版本、编辑和保留旧版本均不自动部署',async({page})=>{
 const state=await fixture(page);await page.goto('/control');await page.getByRole('button',{name:'软件模板',exact:true}).click();await page.getByRole('button',{name:'新建软件模板'}).click();await page.getByLabel('模板名称').fill('夜间英文');await page.getByLabel('日夜模式').selectOption('dark');await page.getByLabel('页面语言').selectOption('en');await page.getByRole('button',{name:'保存草稿'}).click()
 const card=page.locator('.v6-template-item').filter({has:page.getByRole('heading',{name:'夜间英文',exact:true})});await expect(card).toContainText('草稿');await card.getByRole('button',{name:'发布版本'}).click();await expect(card).toContainText('已发布 v1');await card.getByRole('button',{name:'编辑',exact:true}).click();await page.getByLabel('页面语言').selectOption('zh-CN');await page.getByRole('button',{name:'保存草稿'}).click()
 const row=state.catalog.find(t=>t.name==='夜间英文')!;expect((row.versions[0].spec as any).language).toBe('en');expect((row.spec as any).language).toBe('zh-CN');expect(state.writes.some(w=>w.path==='/api/v6/admin/deployments')).toBe(false)
})
test('硬件模板可编辑电平与 GPIO，方向只存在于硬件模板',async({page})=>{
 const state=await fixture(page);await page.goto('/control');await page.getByRole('button',{name:'硬件安装模板',exact:true}).click();await page.getByRole('button',{name:'新建硬件安装模板'}).click();await page.getByLabel('模板名称').fill('竖屏高电平');await page.getByLabel('安装方向').selectOption('true');await page.getByLabel('灯控',{exact:true}).selectOption('true');await page.getByLabel('点亮电平').selectOption('1');await page.getByLabel('红灯 GPIO').selectOption('154');await page.getByLabel('绿灯 GPIO').selectOption('148');await page.getByRole('button',{name:'保存草稿'}).click();expect(state.writes[0].body.spec).toMatchObject({portrait:true,active_level:1,pins:{red:154,green:148,blue:147}})
 await page.getByRole('button',{name:'设备台账',exact:true}).click();await page.getByRole('button',{name:'配置与部署'}).first().click();await expect(page.getByLabel('安装方向')).toHaveCount(0);await expect(page.getByText('保留当前设备配置')).toHaveCount(0)
})
test('模板编辑冲突保持草稿，切换页面也保留编辑',async({page})=>{const state=await fixture(page);await page.goto('/control');await page.getByRole('button',{name:'软件模板',exact:true}).click();await page.locator('.v6-template-item:visible').getByRole('button',{name:'编辑',exact:true}).click();await page.getByLabel('模板名称').fill('保留草稿');await page.getByRole('button',{name:'设备台账',exact:true}).click();await page.getByRole('button',{name:'软件模板',exact:true}).click();await expect(page.getByLabel('模板名称')).toHaveValue('保留草稿');state.conflict=true;await page.getByRole('button',{name:'保存草稿'}).click();await expect(page.getByRole('alert')).toContainText('配置已变化');await expect(page.getByLabel('模板名称')).toHaveValue('保留草稿')})
test('设备、会议室与软件模板使用范围可交叉查看',async({page})=>{const state=await fixture(page);await page.goto('/control');const panel=await selectDeployment(page);await panel.getByRole('button',{name:'检查兼容性与变更范围'}).click();await panel.getByRole('button',{name:'确认部署'}).click();await page.getByRole('button',{name:'会议室',exact:true}).click();await expect(page.locator('tbody tr')).toHaveCount(3);await expect(page.locator('tbody tr').first()).toContainText('测试中文软件 · v1');await expect(page.locator('tbody tr').first()).toContainText('测试横屏硬件 · v1');expect(state.configuration.devices[state.devices[0].id].hardware_id).toBe('hw')})
test('会议室更换软件模板须明确确认影响范围',async({page})=>{const state=await fixture(page);state.configuration.rooms.omm_beijing={room_id:'omm_beijing',software_id:'other',software_version:1,revision:4,controller_id:state.devices[0].id,rules:{owner:'official',mode:'off',early_minutes:5,grace_minutes:10,release_delay_seconds:60},policy_state:'applied',error:'',room_name:'同名会议室',location:'北京'};await page.goto('/control');const panel=await selectDeployment(page);await expect(panel.getByText('更换该会议室软件模板，并更新其所有已关联设备')).toBeVisible();await panel.getByLabel('更换该会议室软件模板，并更新其所有已关联设备').check();await panel.getByRole('button',{name:'检查兼容性与变更范围'}).click();expect(state.writes.at(-1)?.body).toMatchObject({replace_room_software:true,expected_room_revision:4})})
test('日志展示人名、设备、模板与字段差异',async({page})=>{await fixture(page);await page.goto('/control');await page.getByRole('button',{name:'操作记录'}).click();const row=page.locator('tbody tr');await expect(row).toContainText('测试管理员');await expect(row).toContainText('设备 ABC234');await expect(row).toContainText('测试中文软件');await row.getByText('变更明细').click();await expect(row).toContainText('语言：中文 → English')})
test('窄屏模板编辑不会横向溢出',async({page})=>{await fixture(page);await page.setViewportSize({width:390,height:844});await page.goto('/control');await page.getByRole('button',{name:'软件模板',exact:true}).click();await page.getByRole('button',{name:'新建软件模板'}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'/tmp/roombeacon-configuration-mobile.png',fullPage:true})})
test('批量部署在预览后提交固定版本和设备修订号',async({page})=>{
 const state=await fixture(page);await page.route('**/api/v6/admin/deployment-batches/preview',route=>route.fulfill({json:{code:0,data:{devices:[{code:'ABC234',room_name:'同名会议室',hardware:'测试横屏硬件'}]}}}));await page.goto('/control');await page.locator('tbody tr').first().getByRole('checkbox').check();await page.getByLabel('批量硬件模板',{exact:true}).selectOption('hw');await page.getByLabel('批量软件模板',{exact:true}).selectOption('sw');await page.getByRole('button',{name:'检查批量部署',exact:true}).click();await expect(page.getByText('实际影响 1 台设备')).toBeVisible();await page.getByRole('button',{name:'确认批量部署',exact:true}).click();expect(state.writes.at(-1)?.body).toMatchObject({devices:{[state.devices[0].id]:2},hardware_version:1,software_version:1})
})
test('软件模板预览即使服务器允许主控签到也保持只读',async({page})=>{
 await fixture(page);const now=Date.now();await page.route('**/api/room-control/preview?**',route=>route.fulfill({json:{code:0,data:{room:{room_id:'omm_beijing',name:'预览会议室',capacity:8,enabled:true},events:[],synced_at:new Date(now).toISOString(),valid_until:new Date(now+60000).toISOString(),server_time:new Date(now).toISOString(),titles_available:true,usage_owner:'v5'}}}));await page.route('**/api/room-control/usage/omm_beijing',route=>route.fulfill({json:{code:0,data:{control_confirm_enabled:true,usage:{room_id:'omm_beijing',valid_until:new Date(now+60000).toISOString(),policy:{owner:'v5',mode:'observe'},record:null,can_confirm:true}}}}));await page.goto('/control');await page.getByRole('button',{name:'软件模板',exact:true}).click();await page.locator('.v6-template-item:visible').getByRole('button',{name:'编辑',exact:true}).click();await page.getByLabel('签到方案',{exact:true}).selectOption('v5');await page.getByLabel('预览会议室').selectOption('omm_beijing');await page.getByRole('button',{name:'预览当前草稿',exact:true}).click();await expect(page.getByText('V5 预览 · 操作不可用')).toBeVisible();await expect(page.getByRole('button',{name:'签到',exact:true})).toHaveCount(0)
})
