import {test,expect} from '@playwright/test'
import {fixture,selectDeployment} from './configuration.fixture'
test('飞书登录后按硬件、软件、会议室顺序部署并等待回执',async({page})=>{
 const state=await fixture(page,'admin',false);state.devices[0].status='pending';state.devices[0].room_id=''
 await page.goto('/');await expect(page).toHaveURL(/\/control$/)
 await expect(page.getByLabel('主控凭证')).toHaveCount(0)
 await page.route('**/api/v6/auth/feishu/start',async route=>{state.logged=true;await route.fulfill({status:302,headers:{location:'/control'}})})
 await page.getByRole('link',{name:'飞书扫码 / 快捷登录'}).click()
 await expect(page.getByText('ABC 234',{exact:true})).toBeVisible()
 const panel=await selectDeployment(page)
 await panel.getByLabel('分配会议室').selectOption('omm_beijing')
 await panel.getByRole('button',{name:'检查兼容性与变更范围'}).click()
 await expect(panel.getByRole('button',{name:'确认部署'})).toBeVisible()
 expect(state.writes.filter(w=>w.path==='/api/v6/admin/deployments')).toHaveLength(0)
 await panel.getByRole('button',{name:'确认部署'}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(page.getByText('等待设备应用',{exact:true})).toBeVisible()
 expect(state.writes.at(-1)?.body).toMatchObject({expected_revision:2,hardware_id:'hw',software_id:'sw',room_id:'omm_beijing'})
})
test('待授权退出会话失败可以重试，成功后隐藏退出入口',async({page})=>{
 const state=await fixture(page,'pending');await page.goto('/control');await expect(page.getByRole('alert')).toContainText('等待管理员')
 await page.route('**/api/v6/auth/logout',r=>r.fulfill({status:503,json:{code:503}}));await page.getByRole('button',{name:'退出登录'}).click();await expect(page.getByRole('alert')).toContainText('服务暂不可用');expect(state.logged).toBe(true)
 await page.unroute('**/api/v6/auth/logout');const req=page.waitForRequest('**/api/v6/auth/logout');await page.getByRole('button',{name:'退出登录'}).click();expect((await req).headers()['x-rb-logout']).toBe('1');await expect(page.getByRole('button',{name:'退出登录'})).toHaveCount(0)
})
for(const role of ['admin','viewer'])test(`${role}后台退出清理会话`,async({page})=>{const state=await fixture(page,role);await page.goto('/control');await page.getByRole('button',{name:'退出登录'}).click();await expect(page.getByRole('heading',{name:'飞书登录会议灯塔'})).toBeVisible();expect(state.logged).toBe(false)})
test('未授权和失败回调保留登录入口',async({page})=>{await fixture(page,'pending');await page.goto('/control');await expect(page.getByRole('alert')).toContainText('等待管理员');await expect(page.getByRole('button',{name:'账号权限'})).toHaveCount(0);await expect(page.getByRole('link',{name:'飞书扫码 / 快捷登录'})).toBeVisible()})
test('企业登录不可用不展示密码入口',async({page})=>{await fixture(page,'admin',false);await page.route('**/api/v6/auth/options',r=>r.fulfill({json:{data:{feishu:false}}}));await page.goto('/');await expect(page.getByText('飞书登录暂不可用，请联系管理员。')).toBeVisible();await expect(page.locator('input[type=password]')).toHaveCount(0)})
test('只读账号不能部署、编辑模板或修改房间核验',async({page})=>{await fixture(page,'viewer');await page.goto('/control');await expect(page.getByRole('button',{name:'账号权限'})).toHaveCount(0);await page.getByRole('button',{name:'查看',exact:true}).first().click();await expect(page.getByLabel('分配会议室')).toBeDisabled();await expect(page.getByRole('button',{name:'远程刷新'})).toHaveCount(0);await page.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'软件模板',exact:true}).click();await expect(page.getByRole('button',{name:'新建软件模板'})).toHaveCount(0)})
test('离线与应用错误显示清楚，支持分组短码搜索',async({page})=>{const state=await fixture(page);state.devices[0].online=false;state.devices[0].error='灯控失败';await page.goto('/control');await page.getByLabel('搜索设备').fill('ABC 234');await expect(page.locator('tbody tr')).toHaveCount(1);await expect(page.getByText('应用异常',{exact:true})).toBeVisible();await expect(page.getByText('已激活 · 离线',{exact:true})).toBeVisible()})
test('部署冲突保留模板选择和编辑内容',async({page})=>{const state=await fixture(page);await page.goto('/control');const panel=await selectDeployment(page);state.conflict=true;await panel.getByRole('button',{name:'检查兼容性与变更范围'}).click();await expect(panel.getByRole('alert')).toContainText('配置已变化');await expect(panel.getByLabel('软件模板',{exact:true})).toHaveValue('sw')})
test('受管门牌凭证失效保持未知',async({page})=>{await page.route('**/api/meeting-rooms/display',r=>r.fulfill({status:401,json:{code:401}}));await page.goto('/?version=v6&managed=1');await expect(page.getByRole('heading',{name:'绑定会议门牌'})).toHaveCount(0);await expect(page.locator('main')).toHaveAttribute('data-terminal-state','unknown')})
