bind 127.0.0.1
protected-mode yes
port 6380
daemonize no
logfile ""
dir /data/roombeacon/shared/redis
dbfilename dump.rdb
appendonly yes
appendfsync everysec
save 900 1
save 300 10
save 60 10000
maxmemory 2gb
maxmemory-policy noeviction
