import {inject,type ComputedRef,type InjectionKey} from 'vue'
export const displayLanguage:InjectionKey<ComputedRef<string>>=Symbol('displayLanguage')
const english:Record<string,string>={
  "日间": "Day",
  "夜间": "Night",
  "城市待配置": "City not configured",
  "手动预览": "Preview",
  "始终白天": "Always day",
  "状态暂不可确认": "Status unavailable",
  "会议室已停用": "Room disabled",
  "使用中": "In use",
  "正在使用": "In use",
  "即将开始": "Starting soon",
  "空闲可用": "Available",
  "正在获取会议室": "Loading room",
  "正在同步": "Syncing",
  "分钟": "min",
  "距本场结束还有": "Time remaining",
  "距下场开始还有": "Next meeting in",
  "当前可用至": "Available until",
  "历史预约空档至": "Previously available until",
  "全天无后续预约": "No more meetings today",
  "暂无可参考的后续预约": "No upcoming schedule available",
  "当前会议": "Current meeting",
  "下一场会议": "Next meeting",
  "组织者 ·": "Organizer ·",
  "信息不可见": "Not available",
  "已预约会议": "Reserved meeting",
  "暂不可使用": "Unavailable",
  "等待日程同步": "Waiting for schedule",
  "正在确认最新预约状态": "Checking latest availability",
  "后续会议": "Upcoming meetings",
  "本场与下一场": "Current and next",
  "今日安排": "Today’s schedule",
  "· 上次同步数据": "· Last synced data",
  "今天": "Today",
  "预约": "Reserved",
  "进行中": "In progress",
  "下一场": "Next",
  "待开始": "Upcoming",
  "暂无后续会议": "No upcoming meetings",
  "今日全天空闲": "No meetings today",
  "今日会议已结束": "Today’s meetings have ended",
  "会议室当前已停用": "This room is disabled",
  "为下一次交流，留出空间": "Space for your next conversation",
  "人 · 会议空间": "people · meeting space",
  "等待获取日程": "Waiting for schedule",
  "近 12 小时": "12-hour view",
  "预约时间轴": "Booking timeline",
  "可约": "Available",
  "已约": "Reserved",
  "已结束": "Ended",
  "● 日程已同步": "● Schedule synced",
  "● 日程待更新": "● Awaiting update",
  "· 飞书预约日程": "· Feishu bookings",
  "部分会议主题不可见": "Some meeting titles are unavailable",
  "历史日程 · 最后同步": "Past schedule · Last synced",
  "· 正在重试，当前状态待确认": "· Retrying; current status unknown",
  "同步失败，正在重试": "Sync failed; retrying",
  "凭证已失效，请重新绑定": "Credentials expired; contact administrator",
  "本房间使用 V5 确认，请切换到 V5 页面": "This room uses V5 check-in; switch to V5",
  "飞书扫码签到": "Scan to check in",
  "打开飞书扫一扫": "Scan with Feishu",
  "签到结果请以飞书页面为准": "Check-in result is shown in Feishu",
  "请签到": "Please check in",
  "已确认使用": "Checked in",
  "请确认使用": "Please confirm use",
  "已超时 · 仅记录": "Timed out · recorded only",
  "正在安排提前结束": "Scheduling early end",
  "正在释放预约": "Releasing booking",
  "本次预约已释放": "Booking released",
  "自动释放已暂停": "Automatic release paused",
  "释放结果待核实": "Release result unverified",
  "释放未成功": "Release failed",
  "尚未确认 · 即将释放": "Not checked in · release pending",
  "正在核验释放条件": "Checking release conditions",
  "V5 预览 · 操作不可用": "V5 preview · actions unavailable",
  "签到暂不可用": "Check-in unavailable",
  "确认状态待同步": "Awaiting check-in status",
  "本房间使用官方方案，请切换到 V4": "This room uses official check-in; switch to V4",
  "确认使用已关闭": "Check-in disabled",
  "状态待核实": "Status unverified",
  "当前没有可签到的预约": "No booking available for check-in",
  "等待下一场确认窗口": "Waiting for next check-in window",
  "本次预约受保护，不会自动释放": "This booking is protected from automatic release",
  "本场预约已保留": "This booking has been retained",
  "观察模式 · 仅记录，不自动释放": "Observation mode · no automatic release",
  "自动释放已由管理员暂停": "Automatic release paused by administrator",
  "正在核验预约，暂不自动释放": "Verifying booking; automatic release on hold",
  "自动释放待管理员登记本次预约": "Administrator must verify this booking before release",
  "未签到将按规则释放预约": "Bookings without check-in may be released",
  "签到截止": "Check-in deadline",
  "后核验释放，仍可补确认": "release verification begins; check-in still available",
  "已过确认截止时间，请使用下一场预约测试": "Check-in deadline has passed",
  "释放倒计时": "Release in",
  "签到倒计时": "Check in within",
  "仍可签到保留本场会议": "Check in to retain this booking",
  "正在同步释放状态": "Syncing release status",
  "正在提交…": "Submitting…",
  "签到": "Check in",
  "V5 功能尚未启用，预约展示不受影响": "V5 not enabled; schedule display remains available",
  "当前服务器尚未支持 V5，预约展示不受影响": "V5 unavailable; schedule display remains available",
  "操作凭证已失效，请重新绑定": "Action credentials expired; contact administrator",
  "预约或规则已变化，请刷新后核对": "Booking or policy changed; refresh to verify",
  "操作结果待核实，请等待重新同步": "Action result unverified; waiting to sync",
  "设备设置": "Device settings",
  "启用确认操作": "Enable check-in",
  "滚动12小时预约时间轴": "Rolling 12-hour booking timeline",
  "本场会议进度": "Meeting progress",
  "扫码预订": "Scan to book",
  "预约入口待接入": "Booking link unavailable",
  "绑定会议门牌": "Bind room display",
  "请输入管理员为这间会议室生成的设备凭证。": "Enter the room credentials provided by your administrator.",
  "绑定并显示": "Bind and display"
}
export function translateDisplayText(value:string,language:string){return language==='en'?(english[value] || value):value}
export function useDisplayText(){const language=inject(displayLanguage);return (value:string)=>translateDisplayText(value,language?.value || 'zh-CN')}
